-- return {
--   "folke/tokyonight.nvim",
--   priority = 1000,
--   config = function()
--     local bg = "#011628"
--     local bg_dark = "#011423"
--     local bg_highlight = "#143652"
--     local bg_search = "#0A64AC"
--     local bg_visual = "#275378"
--     local fg = "#CBE0F0"
--     local fg_dark = "#B4D0E9"
--     local fg_gutter = "#627E97"
--     local border = "#547998"
--
--     require("tokyonight").setup({
--       style = "night",
--       on_colors = function(colors)
--         colors.bg = bg
--         colors.bg_dark = bg_dark
--         colors.bg_float = bg_dark
--         colors.bg_highlight = bg_highlight
--         colors.bg_popup = bg_dark
--         colors.bg_search = bg_search
--         colors.bg_sidebar = bg_dark
--         colors.bg_statusline = bg_dark
--         colors.bg_visual = bg_visual
--         colors.border = border
--         colors.fg = fg
--         colors.fg_dark = fg_dark
--         colors.fg_float = fg
--         colors.fg_gutter = fg_gutter
--         colors.fg_sidebar = fg_dark
--       end
--     })
--     vim.cmd("colorscheme tokyonight")
--   end
-- }

-- return {
-- 	"catppuccin/nvim",
-- 	name = "catppuccin",
-- 	priority = 1000,
-- 	config = function()
-- 		require("catppuccin").setup({
-- 			flavour = "macchiato", -- latte, frappe, macchiato, mocha
-- 			integrations = {
-- 				treesitter = true,
-- 				native_lsp = { enabled = true },
-- 				telescope = true,
-- 				gitsigns = true,
-- 				cmp = true,
-- 				nvimtree = true,
-- 				notify = true,
-- 			},
-- 		})
-- 		vim.cmd.colorscheme("catppuccin") -- uses the flavour above
-- 	end,
-- }

-- return {
-- 	"folke/tokyonight.nvim",
-- 	lazy = false, -- load during startup
-- 	priority = 1000, -- load before all other UI plugins
-- 	opts = {
-- 		-- core style
-- 		style = "moon", -- explicit, even though it's the default
-- 		light_style = "day",
-- 		transparent = false, -- set true if you want terminal background to show
-- 		terminal_colors = true,
--
-- 		-- syntax styles
-- 		styles = {
-- 			comments = { italic = true },
-- 			keywords = { italic = true },
-- 			functions = {},
-- 			variables = {},
-- 			-- background style for sidebars / floats
-- 			sidebars = "dark", -- "dark", "transparent" or "normal"
-- 			floats = "dark",
-- 		},
--
-- 		-- dim inactive windows? (good with LSP + splits)
-- 		dim_inactive = false,
--
-- 		-- lualine section headers bold or not
-- 		lualine_bold = false,
--
-- 		-- plugin integrations
-- 		plugins = {
-- 			-- we are using lazy.nvim, so:
-- 			all = false, -- don't blindly enable everything
-- 			auto = true, -- auto-detect and enable support for installed plugins
-- 			-- with auto = true, it will handle:
-- 			-- treesitter, lsp, telescope, gitsigns, nvim-cmp, nvim-tree,
-- 			-- nvim-notify, noice, lspsaga, trouble, which-key, etc.
-- 		},
--
-- 		-- hooks if you ever want to tweak colors manually
-- 		on_colors = function(colors)
-- 			-- example: you can tweak palette here later if you feel like it
-- 			-- colors.bg = "#000000"
-- 		end,
--
-- 		on_highlights = function(hl, colors)
-- 			-- example: borderless telescope (from the README), customize later if desired
-- 			-- local prompt = "#2d3149"
-- 			-- hl.TelescopeNormal = { bg = colors.bg_dark, fg = colors.fg_dark }
-- 			-- ...
-- 		end,
-- 	},
--
-- 	config = function(_, opts)
-- 		-- make sure truecolor is on
-- 		vim.o.termguicolors = true
--
-- 		-- apply Tokyonight configuration
-- 		require("tokyonight").setup(opts)
--
-- 		-- and actually use the Moon variant
-- 		vim.cmd.colorscheme("tokyonight-moon")
-- 	end,
-- }

-- return {
-- 	"navarasu/onedark.nvim",
-- 	name = "onedark",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		-- Enable true color support
-- 		vim.o.termguicolors = true
--
-- 		-- Configure onedark
-- 		require("onedark").setup({
-- 			style = "dark", -- choose from 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer', 'light'
-- 			transparent = false, -- set true if you prefer no background
-- 			term_colors = true, -- update terminal colors
-- 			ending_tildes = false, -- hide ~ lines after buffer end
-- 			cmp_itemkind_reverse = false,
--
-- 			code_style = {
-- 				comments = "italic",
-- 				keywords = "none",
-- 				functions = "none",
-- 				strings = "none",
-- 				variables = "none",
-- 			},
--
-- 			lualine = {
-- 				transparent = false,
-- 			},
--
-- 			-- optional: override particular colors or highlight-groups
-- 			colors = {},
-- 			highlights = {},
--
-- 			diagnostics = {
-- 				darker = true, -- darker colors for diagnostics (LSP / lint)
-- 				undercurl = true, -- use undercurl instead of underline
-- 				background = true, -- use background color for virtual text
-- 			},
-- 		})
--
-- 		-- Apply the theme
-- 		require("onedark").load()
-- 	end,
-- }
--

return {
	"neanias/everforest-nvim",
	name = "everforest",
	lazy = false,
	priority = 1000,
	config = function()
		vim.o.termguicolors = true
		require("everforest").setup({
			background = "hard", -- "hard", "medium", "soft"
			italics = true,
		})
		vim.cmd.colorscheme("everforest")
	end,
}
